"""creation initiale

Revision ID: 11188f1182f1
Revises:
Create Date: 2026-08-20 14:25:56.477036
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '11188f1182f1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'compteur',
        sa.Column('annee', sa.Integer(), nullable=False),
        sa.Column('sequence', sa.Integer(), nullable=False),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('annee'),
    )
    op.create_table(
        'jeton_connexion',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('empreinte', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
        sa.Column('utilise_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('empreinte'),
    )
    with op.batch_alter_table('jeton_connexion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jeton_connexion_email'), ['email'], unique=False)

    op.create_table(
        'journal_audit',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('entite', sa.String(length=40), nullable=False),
        sa.Column('entite_id', sa.String(length=60), nullable=False),
        sa.Column('action', sa.String(length=40), nullable=False),
        sa.Column('acteur', sa.String(length=255), nullable=False),
        sa.Column('ip', sa.String(length=60), nullable=True),
        sa.Column('details', sa.JSON(), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('journal_audit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_audit_cree_le'), ['cree_le'], unique=False)
        batch_op.create_index('ix_journal_entite', ['entite', 'entite_id'], unique=False)

    op.create_table(
        'limite_debit',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('cle', sa.String(length=200), nullable=False),
        sa.Column('fenetre_debut', sa.DateTime(timezone=True), nullable=False),
        sa.Column('compteur', sa.Integer(), nullable=False),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cle', 'fenetre_debut', name='uq_limite_cle_fenetre'),
    )
    with op.batch_alter_table('limite_debit', schema=None) as batch_op:
        batch_op.create_index('ix_limite_fenetre', ['fenetre_debut'], unique=False)

    op.create_table(
        'utilisateur',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('nom', sa.String(length=100), nullable=False),
        sa.Column('prenoms', sa.String(length=150), nullable=False),
        sa.Column('matricule', sa.String(length=20), nullable=False),
        sa.Column('fonction', sa.String(length=150), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('email_verifie_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'role',
            sa.Enum('EMPLOYEE', 'HR', 'ADMIN', name='role', native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column('actif', sa.Boolean(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('matricule'),
    )
    op.create_table(
        'ordre_mission',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('numero', sa.String(length=40), nullable=False),
        sa.Column('demandeur_id', sa.String(length=36), nullable=False),
        sa.Column('nom', sa.String(length=100), nullable=False),
        sa.Column('prenoms', sa.String(length=150), nullable=False),
        sa.Column('matricule', sa.String(length=20), nullable=False),
        sa.Column('fonction', sa.String(length=150), nullable=False),
        sa.Column('analytique', sa.String(length=50), nullable=True),
        sa.Column('objet', sa.String(length=300), nullable=False),
        sa.Column('lieu', sa.String(length=200), nullable=False),
        sa.Column('date_depart', sa.DateTime(timezone=True), nullable=False),
        sa.Column('date_retour', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'transport_type',
            sa.Enum(
                'VEHICULE_ETABLISSEMENT',
                'VEHICULE_PERSONNEL',
                'VEHICULE_LOCATION',
                'TRANSPORT_EN_COMMUN',
                name='transport',
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column('transport_detail', sa.String(length=200), nullable=True),
        sa.Column('litres_gasoil', sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column(
            'statut',
            sa.Enum(
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'REJECTED',
                'CANCELLED',
                name='statut_mission',
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column('motif_refus', sa.Text(), nullable=True),
        sa.Column('soumis_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column('decide_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column('decide_par_id', sa.String(length=36), nullable=True),
        sa.Column('decide_par_nom', sa.String(length=200), nullable=True),
        sa.Column('decide_par_email', sa.String(length=255), nullable=True),
        sa.Column('relances', sa.Integer(), nullable=False),
        sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
        sa.Column('modifie_le', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ['demandeur_id'],
            ['utilisateur.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero'),
    )
    with op.batch_alter_table('ordre_mission', schema=None) as batch_op:
        batch_op.create_index('ix_ordre_demandeur_statut', ['demandeur_id', 'statut'], unique=False)
        batch_op.create_index('ix_ordre_statut_soumis', ['statut', 'soumis_le'], unique=False)

    op.create_table(
        'jeton_approbation',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('empreinte', sa.String(length=64), nullable=False),
        sa.Column('mission_id', sa.String(length=36), nullable=False),
        sa.Column('action', sa.String(length=10), nullable=False),
        sa.Column('expire_le', sa.DateTime(timezone=True), nullable=False),
        sa.Column('utilise_le', sa.DateTime(timezone=True), nullable=True),
        sa.Column('cree_le', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['mission_id'], ['ordre_mission.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('empreinte'),
    )
    with op.batch_alter_table('jeton_approbation', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_jeton_approbation_mission_id'), ['mission_id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jeton_approbation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jeton_approbation_mission_id'))

    op.drop_table('jeton_approbation')
    with op.batch_alter_table('ordre_mission', schema=None) as batch_op:
        batch_op.drop_index('ix_ordre_statut_soumis')
        batch_op.drop_index('ix_ordre_demandeur_statut')

    op.drop_table('ordre_mission')
    op.drop_table('utilisateur')
    with op.batch_alter_table('limite_debit', schema=None) as batch_op:
        batch_op.drop_index('ix_limite_fenetre')

    op.drop_table('limite_debit')
    with op.batch_alter_table('journal_audit', schema=None) as batch_op:
        batch_op.drop_index('ix_journal_entite')
        batch_op.drop_index(batch_op.f('ix_journal_audit_cree_le'))

    op.drop_table('journal_audit')
    with op.batch_alter_table('jeton_connexion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jeton_connexion_email'))

    op.drop_table('jeton_connexion')
    op.drop_table('compteur')
    # ### end Alembic commands ###
